#ifndef QTNATIVEUTILS_GLOBAL_H
#define QTNATIVEUTILS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTNATIVEUTILS_LIBRARY)
#  define QTNATIVEUTILSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTNATIVEUTILSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTNATIVEUTILS_GLOBAL_H
