# Read the Docs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"

sphinx:
  fail_on_warning: true
  configuration: doc/source/conf.py

build:
  apt_packages:
    - xvfb
    - libglu1-mesa-dev
    - libgl1-mesa-dev
    - libxi-dev
    - libglfw3-dev
    - libgles2-mesa-dev
    - mesa-utils

python:
  install:
    - requirements: doc/requirements.txt
